import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "../context/Auth";
import Header from "../components/Header";
import Footer from "@/components/Footer";
import { TaskProvider } from "@/context/Task";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <TaskProvider>
          <Header/>
        {children}
          <Footer/>
          </TaskProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
